# Generated by Django 5.2.4 on 2025-08-24 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('validated', 'Validée'), ('final', 'Finale'), ('archived', 'Archivée')], default='draft', max_length=20)),
                ('validated', models.BooleanField(default=False)),
                ('final_validated', models.BooleanField(default=False)),
                ('ai_feedback_requested', models.BooleanField(default=False)),
                ('ai_feedback_received', models.BooleanField(default=False)),
                ('ai_feedback_status', models.CharField(choices=[('not_requested', 'Non demandée'), ('requested', 'Demandée'), ('processing', 'En cours'), ('completed', 'Terminée')], default='not_requested', max_length=20)),
                ('ai_feedback_data', models.JSONField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
