# Generated by Django 5.2.4 on 2025-08-30 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videosession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
